server.port=8081
server.servlet.context-path=/operations

spring.application.name=OperationsService

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/karyam
spring.datasource.username=root
spring.datasource.password=yourPassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

karyam.jwt.exp-time-in-min=840
karyam.jwt.secrete-key=yourSecretJwtKey

karyam.kafka.project-topic=project-event-topic
karyam.kafka.labor-topic=labor-event-topic
karyam.kafka.attendance-topic=attendance-event-topic
karyam.kafka.vendor-topic=vendor-event-topic
karyam.kafka.expense-topic=expense-event-topic
