server:
  port: 8082
  servlet:
    context-path: /notification
    
debug: true

spring:
  application:
    name: NotificationService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/karyam
    username: root
    password: yourPassword
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: '*'
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    
karyam:
  jwt:
    exp-time-in-min: 840
    secrete-key: yourSecretJwtKey
